# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPUInsAEgpukl1Z2RSsBgznx7uyhhGoJ
"""

import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/Insiya24/datasets/main/WA_Fn-UseC_-HR-Employee-Attrition.csv")

data

data.axes

data.head()

data.tail()

data.tail()

data.dtypes

data.isna().sum()

data.isnull()

data.count()

data['Department'].mode()

data['Department'].fillna('Research & Development', inplace=True)



data.isna().sum()

data['EducationField'].mode()

data['EducationField'].fillna('Life Sciences', inplace=True)

data.isna().sum()

data['EmployeeCount'].mean()

data['EmployeeCount'].fillna(1.0 , inplace=True)

data['EmployeeNumber'].mean()

data['EmployeeNumber'].fillna(1026.0517711171663, inplace=True
)

data['EnvironmentSatisfaction'].mean()

data['EnvironmentSatisfaction'].fillna(2.7229407760381212 , inplace=True)

data['Gender'].mode()

data['Gender'].fillna('Male' , inplace=True)

data.isna().sum()

data['HourlyRate'].mean()

data['HourlyRate'].fillna(65.88207225630539 , inplace = True)

data['JobInvolvement'].mean()

data['JobInvolvement'].fillna(2.732919254658385 , inplace = True)

data['JobLevel'].mean()

data['JobLevel'].fillna(2.0611263736263736 , inplace = True)

data['JobSatisfaction'].mean()

data['JobSatisfaction'].fillna(2.726525017135024 , inplace = True)

data['PercentSalaryHike'].mean()

data['PercentSalaryHike'].fillna(15.220628415300547 , inplace = True)

data.isna().sum()

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

data['Attrition'].value_counts()

data['Attrition'] = le.fit_transform(data['Attrition'])

data['Attrition'].value_counts()



data.dtypes

data['Gender'] = le.fit_transform(data['Gender'])

data['Department'] = le.fit_transform(data['Department'])

data['EducationField'] = le.fit_transform(data['EducationField'])

data['MaritalStatus'] = le.fit_transform(data['MaritalStatus'])

data['OverTime'] = le.fit_transform(data['OverTime'])



data.dtypes

data

import seaborn as sb
import matplotlib. pyplot as mpt
mpt.figure(figsize=(16,16)),
sb.heatmap(data.corr(), annot=True)
mpt.show()